---
- hosts: all
  become: yes
  tasks:
  - name:  in this tasks , i want install apache2 webservers on ubunut
    apt:
      name: apache2
      state: present
  - name: in this tasks, i want start apache2 webservers on ubunut
    service: 
      name: apache2
      state: started
